/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BookmarksLink: typeof import('./components/BookmarksLink.vue')['default']
    BookmarksScroll: typeof import('./components/BookmarksScroll.vue')['default']
    copy: typeof import('./components/ModalPassword copy.vue')['default']
    Favicon: typeof import('./components/Favicon.vue')['default']
    IconMaterialSymbolsFilterAlt: typeof import('~icons/material-symbols/filter-alt')['default']
    IconMaterialSymbolsFilterAltOff: typeof import('~icons/material-symbols/filter-alt-off')['default']
    IconMaterialSymbolsKey: typeof import('~icons/material-symbols/key')['default']
    IconMaterialSymbolsKeyOff: typeof import('~icons/material-symbols/key-off')['default']
    IconMdiApple: typeof import('~icons/mdi/apple')['default']
    IconMdiBookmark: typeof import('~icons/mdi/bookmark')['default']
    IconMdiBookmarkBox: typeof import('~icons/mdi/bookmark-box')['default']
    IconMdiCheck: typeof import('~icons/mdi/check')['default']
    IconMdiCheckBold: typeof import('~icons/mdi/check-bold')['default']
    IconMdiClock: typeof import('~icons/mdi/clock')['default']
    IconMdiCloseThick: typeof import('~icons/mdi/close-thick')['default']
    IconMdiCog: typeof import('~icons/mdi/cog')['default']
    IconMdiDelete: typeof import('~icons/mdi/delete')['default']
    IconMdiEye: typeof import('~icons/mdi/eye')['default']
    IconMdiEyeOff: typeof import('~icons/mdi/eye-off')['default']
    IconMdiFilter: typeof import('~icons/mdi/filter')['default']
    IconMdiFilterOutline: typeof import('~icons/mdi/filter-outline')['default']
    IconMdiFolder: typeof import('~icons/mdi/folder')['default']
    IconMdiFolderOpen: typeof import('~icons/mdi/folder-open')['default']
    IconMdiFolderOutline: typeof import('~icons/mdi/folder-outline')['default']
    IconMdiKey: typeof import('~icons/mdi/key')['default']
    IconMdiKeyPlus: typeof import('~icons/mdi/key-plus')['default']
    IconMdiLock: typeof import('~icons/mdi/lock')['default']
    IconMdiLockOpen: typeof import('~icons/mdi/lock-open')['default']
    IconMdiMagnify: typeof import('~icons/mdi/magnify')['default']
    IconMsFilterAlt: typeof import('~icons/material-symbols/filter-alt')['default']
    Image: typeof import('./components/Image.vue')['default']
    Modal: typeof import('./components/Modal.vue')['default']
    ModalPassword: typeof import('./components/ModalPassword.vue')['default']
    ModalWarning: typeof import('./components/ModalWarning.vue')['default']
    Search: typeof import('./components/Search.vue')['default']
    SearchBar: typeof import('./components/SearchBar.vue')['default']
  }
}
