/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BookmarksLink: typeof import('./components/BookmarksLink.vue')['default']
    BookmarksScroll: typeof import('./components/BookmarksScroll.vue')['default']
    Favicon: typeof import('./components/Favicon.vue')['default']
    IconMaterialSymbolsBookmarkAdd: typeof import('~icons/material-symbols/bookmark-add')['default']
    IconMaterialSymbolsClose: typeof import('~icons/material-symbols/close')['default']
    IconMaterialSymbolsDone: typeof import('~icons/material-symbols/done')['default']
    IconMaterialSymbolsFilterAlt: typeof import('~icons/material-symbols/filter-alt')['default']
    IconMaterialSymbolsFilterAltOff: typeof import('~icons/material-symbols/filter-alt-off')['default']
    IconMaterialSymbolsFolder: typeof import('~icons/material-symbols/folder')['default']
    IconMaterialSymbolsFolderOpen: typeof import('~icons/material-symbols/folder-open')['default']
    IconMaterialSymbolsKey: typeof import('~icons/material-symbols/key')['default']
    IconMaterialSymbolsKeyOff: typeof import('~icons/material-symbols/key-off')['default']
    IconMaterialSymbolsLock: typeof import('~icons/material-symbols/lock')['default']
    IconMaterialSymbolsLockOpen: typeof import('~icons/material-symbols/lock-open')['default']
    IconMaterialSymbolsScheduleOutline: typeof import('~icons/material-symbols/schedule-outline')['default']
    IconMaterialSymbolsSearch: typeof import('~icons/material-symbols/search')['default']
    IconMaterialSymbolsSettings: typeof import('~icons/material-symbols/settings')['default']
    IconMaterialSymbolsVisibility: typeof import('~icons/material-symbols/visibility')['default']
    IconMaterialSymbolsVisibilityOff: typeof import('~icons/material-symbols/visibility-off')['default']
    Modal: typeof import('./components/Modal.vue')['default']
    ModalPassword: typeof import('./components/ModalPassword.vue')['default']
    ModalWarning: typeof import('./components/ModalWarning.vue')['default']
    PageSettings: typeof import('./components/PageSettings.vue')['default']
  }
}
